server:
  port: ${PROD_PORT}
spring:
  application:
    name: tecnoguard
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_PROD_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration/postgres
  jackson:
    serialization:
      write-dates-as-timestamps: false
api:
  security:
    token:
      secret: ${JWT_SECRET}